### DISCUSSION TITLE
Would be nice if there was an option to remove "More Tweets"

### DISCUSSION THREAD

**Discussion by ricardosaracino** [typefully/minimal-twitter#117] [Ideas]
![image](https://user-images.githubusercontent.com/759253/136712840-a27916a3-df32-4985-ba2b-a45ee20d1ea7.png)

**Comment by slorber** [comment]
Can confirm 🤪 this is becoming so annoying

https://twitter.com/sebastienlorber/status/1490704646230482949

**Comment by slorber** [comment]
@thomaswang I think CSS `:has()` may help solve this annoying section problem. It's not widely supported by should be in Chrome quite soon.

Just separating the "more. tweets" section from the rest with a huge padding can be a win for me 👍 

```css
h2 > div:has(> span:contains("More Tweets")) {
  padding-top: 100rem !important;
}
```
